spring:
  application:
    name: pause-aware-streams-app
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    streams:
      application-id: pause-aware-streams-app
      bootstrap-servers: 127.0.0.1:9092
      properties:
        processing.guarantee: exactly_once_v2
        commit.interval.ms: 100
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde

server:
  port: 8080

app:
  flows:
    - topicId: demo
      mainTopic: demo-in
      statusTopic: key-status
      triggerTopic: demo-resume
      outputTopic: demo-out
      bufferStoreName: demo-buffer-store
    - topicId: orders
      mainTopic: orders-in
      statusTopic: key-status
      triggerTopic: orders-resume
      outputTopic: orders-out
      bufferStoreName: orders-buffer-store
    - topicId: payments
      mainTopic: payments-in
      statusTopic: key-status
      triggerTopic: payments-resume
      outputTopic: payments-out
      bufferStoreName: payments-buffer-store
